export const iconData = [
    'management',
    'baseball',
    'Basketball',
    'BellFilled',
    'Bell',
    'AddLocation',
    'Aim',
    'AlarmClock',
    'Apple',
    'ArrowDownBold',
    'Burger',
    'Brush',
    'BrushFilled',
    'RemoveFilled',
    'QuestionFilled',
    'Promotion',
    'Printer',
    'School',
    'Setting',
    'WarningFilled',
    'ZoomOut',
    'WalletFilled',
    'User',
    'ToiletPaper', 'Sunrise', 'Sunny', 'SwitchButton', 'TakeawayBox', 'Ticket',
    'StarFilled', 'Stamp', 'Stopwatch', 'SortDown', 'SemiSelect', 'Search'
]
